# Generated by Django 4.0.6 on 2022-07-19 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_alter_channel_connected_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='adding_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
