# Generated by Django 4.0.6 on 2022-07-19 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_alter_channel_adding_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='adding_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 19, 16, 35, 12, 47590)),
        ),
    ]
