# Generated by Django 4.0.6 on 2022-07-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_alter_channel_adding_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='adding_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
