# Generated by Django 4.0.6 on 2022-07-19 17:17

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connection', '0006_alter_channel_adding_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='adding_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.RemoveField(
            model_name='channel',
            name='connected_users',
        ),
        migrations.AddField(
            model_name='channel',
            name='connected_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
