# Generated by Django 4.0.6 on 2022-07-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0007_alter_channel_adding_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
