# Generated by Django 4.0.6 on 2022-07-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0008_channel_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel',
        ),
    ]
